### ISSUE TITLE
scrollable ToC

### ISSUE THREAD

**Issue by iodeo** [jbellue/stum1b#1]
Salut,

Merci pour ta page que je consulte régulièrement !

Lorsque je consulte la page sur un petit écran, et/ou que la table des matières se développe jusqu'aux sous-sous-...-sous-paragraphe, on n'en voit plus le bas. 
Ca peut se faire en ajoutant une ligne de css à la fin de la classe #tableOfContents (l.126):
`overflow-y: auto;`
(testé sur firefox)

PS: n'étant pas un grand utilisateur de github, j'ai toujours du mal à trouver le lien jbellue.github.io/stum1b qui se cache dans les infos du repo. Ce serait peut être plus visible en première ligne du readme ?

**Comment by jbellue** [comment]
Je reconnais que je n'avais jamais pensé que quelqu'un irait voir ce site depuis un mobile, alors l'accessibilité est très minimale !
la table des matières à reçu son ascenceur, et un lien a été ajouté au titre du readme.
Merci !
N'hésite pas à créer un pull request pour ce genre de suggestions !
