### ISSUE TITLE
erreur typo

### ISSUE THREAD

**Issue by iodeo** [jbellue/stum1b#2]
salut,
comme tu le vois je me sers pas mal du stum1b en ce moment !
j'ai trouvé une petite erreur dans le document en travaillant sur les accents:
tableau en 2.3.5.1.2: TS Guide affiche ¨ et pas "
c'est à la ligne 3926 de ton html

**Comment by jbellue** [comment]
Je suis content que tout mon travail serve !
J'ai vérifié, tu as raison, c'est bien un tréma. C'est changé, merci !
